from client_thread_archive import TOOL_DEFINITIONS as ARCHIVE_TOOL_DEFINITIONS
TOOL_DEFINITIONS = [
    {"name": "whoami", "description": "Show the current authorized CLIENT account and scopes.",
     "inputSchema": {"type": "object", "properties": {}},
     "annotations": {"readOnlyHint": True}},
    {"name": "get_context", "description": "Read inherited daughter Sfera Markdown context for a CLIENT path.",
     "inputSchema": {"type": "object", "properties": {"path": {"type": "string"}}},
     "annotations": {"readOnlyHint": True}},
    {"name": "read_document", "description": "Read one canonical CLIENT Markdown document and its version hash.",
     "inputSchema": {"type": "object", "properties": {"logical_key": {"type": "string"}},
                     "required": ["logical_key"]}, "annotations": {"readOnlyHint": True}},
    {"name": "search_knowledge", "description": "Search active CLIENT knowledge with source and epistemic status.",
     "inputSchema": {"type": "object", "properties": {"query": {"type": "string"},
                     "limit": {"type": "integer", "minimum": 1, "maximum": 50}},
                     "required": ["query"]}, "annotations": {"readOnlyHint": True}},
    {"name": "get_knowledge", "description": "Read one canonical active CLIENT knowledge item.",
     "inputSchema": {"type": "object", "properties": {"id": {"type": "string"}},
                     "required": ["id"]}, "annotations": {"readOnlyHint": True}},
    {"name": "list_skills", "description": "List daughter skills; optionally include unverified candidates.",
     "inputSchema": {"type": "object", "properties": {"include_candidates": {"type": "boolean"}}},
     "annotations": {"readOnlyHint": True}},
    {"name": "get_skill", "description": "Read a daughter skill procedure and its validation status.",
     "inputSchema": {"type": "object", "properties": {"key": {"type": "string"}},
                     "required": ["key"]}, "annotations": {"readOnlyHint": True}},
    {"name": "start_task", "description": "Create an owned CLIENT task and record its supplied request.",
     "inputSchema": {"type": "object", "properties": {"request": {"type": "string"},
                     "criteria": {"type": "array", "items": {"type": "string"}},
                     "task_id": {"type": "string"}}, "required": ["request"]}},
    {"name": "record_message", "description": "Archive a supplied message in an enabled private thread; never writes shared dialogue.",
     "inputSchema": {"type": "object", "properties": {"task_id": {"type": "string"},
                     "thread_id": {"type": "string"}, "source_sequence": {"type": "integer", "minimum": 0},
                     "body": {"type": "string"}, "source_message_id": {"type": "string"},
                     "role": {"type": "string", "enum": ["user", "assistant"]},
                     "completeness": {"type": "string", "enum": ["exact", "partial", "redacted"]},
                     "redaction_note": {"type": "string"}},
                     "required": ["thread_id", "source_sequence", "body", "source_message_id", "role", "completeness"]}},
    {"name": "finish_task", "description": "Record an immutable CLIENT task outcome and queue protocolization.",
     "inputSchema": {"type": "object", "properties": {"task_id": {"type": "string"},
                     "status": {"type": "string", "enum": ["succeeded", "partial", "failed"]},
                     "summary": {"type": "object"}},
                     "required": ["task_id", "status", "summary"]}},
]
